<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LogicalCircuits_Ex04" Id="{900b4993-f1e8-471f-8779-fdb4f71cd3f9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM LogicalCircuits_Ex04
VAR
	S1 						: digitalInput_NO;
	S2						: DigitalInput_NO;
	P1 						: digitaloutput;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF S1.isOn OR S2.isOn THEN
	P1.On();
ELSE
	P1.Off();
END_IF]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>