<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LogicalCircuits_Ex08" Id="{50decc6a-c2c3-4ec9-951a-5beef602821e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM LogicalCircuits_Ex08
VAR
	S1					: DigitalInput_NO;
	S2					: DigitalInput_NO;
	P1 					: DigitalOutput;
	P2 					: DigitalOutput;
	P3 					: DigitalOutput;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF S1.isOn AND S2.isOff THEN
	P1.On();
ELSIF S1.isOff AND S2.isOn THEN
	P2.On();
ELSIF S1.isOn AND S2.isOn THEN 
	P1.Off();
	P2.Off();
	P3.On();
END_IF]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>