<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LogicalCircuits_Ex01" Id="{69b0466a-27a2-4fbb-9e44-83f2117ad852}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM LogicalCircuits_Ex01
VAR
	S1					: WorkshopLibrary.DigitalInputNO;
	P1					: WorkshopLibrary.DigitalOutput;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Evaluate inputs
S1(input := GVL_IO.input01);

// process outputs
P1(on:=S1.isActive, output=>GVL_IO.output01);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>