<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LogicalCircuits" Id="{2d6c14dc-8d96-4ba2-9b00-e1c9eb674b9a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM LogicalCircuits
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//LogicalCircuits_Ex01();
//LogicalCircuits_Ex02();
//LogicalCircuits_Ex03();
//LogicalCircuits_Ex04();
//LogicalCircuits_Ex05();
//LogicalCircuits_Ex06();
//LogicalCircuits_Ex07();
//LogicalCircuits_Ex08();
//LogicalCircuits_Ex09();
LogicalCircuits_Ex10();
//LogicalCircuits_Ex11();
//LogicalCircuits_Ex12();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>