<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LogicalCircuits_Ex12" Id="{cb3738d7-dc39-4798-b9c8-be3da4cc71cd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM LogicalCircuits_Ex12
VAR
	sensorB2		 		: digitalInput_NO;
	sensorB1		 		: digitalInput_NO;
	S1				 		: digitalInput_NO;
	S2				 		: digitalInput_NO;
	
	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>