<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LogicalCircuits_Ex02" Id="{928081cd-c731-4064-9f20-4dd0f589a3e1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM LogicalCircuits_Ex02
VAR
	S1						: DigitalInput_NO;
	S2						: DigitalInput_NO;
	P1						: DigitalOutput;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF S1.isOn and S2.isOn THEN
	P1.On();
ELSE
	P1.Off();
END_IF]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>