<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="timers_ex05" Id="{235d3620-40e2-4d05-9d57-165b3dbeea1c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK timers_ex05
VAR_INPUT
	stand			: Switch_2P;
END_VAR
VAR_OUTPUT
	P1				: DigitalOutput;
	P2				: DigitalOutput;
END_VAR
VAR
	Timer1_ex04		: TON;
	Timer2_ex04		: Tof; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>