<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="_TemplateFB" Id="{5b3ac5df-9d93-4b84-8bff-2d4073da45ad}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no_explicit_call' := 'do not call this POU directly, call execute'} 
FUNCTION_BLOCK _TemplateFB
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// NO CODE HERE, USE execute]]></ST>
    </Implementation>
    <Method Name="execute" Id="{f125a433-0a62-494c-b1c6-308ef7e187e2}">
      <Declaration><![CDATA[METHOD execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>