<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Scale" Id="{5d67843b-3530-4c9b-9c4d-73d68b9ee1cc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Scale
VAR_INPUT
	fIN				: REAL;
	fIN_min 		: REAL;
	fIN_max			: REAL;
	fOUT_min		: REAL;
	fOUT_max 		: REAL;
END_VAR
VAR_OUTPUT
	fOUT 			: REAL;	
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fOUT := fOUT_min + (fIN - fIN_MIN) * (fOUT_max - fOUT_min) / (fIN_max - fIN_min);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>