<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="DigitalInput_NC" Id="{e7be2133-8661-4bf4-ae28-0b019ca4c44b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK DigitalInput_NC
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	DIinputNC at %I* : bool;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="broken" Id="{b7bb4338-06a5-48c8-b39b-19573dd708d6}">
      <Declaration><![CDATA[PROPERTY broken : BOOL]]></Declaration>
      <Get Name="Get" Id="{3e4733aa-b156-4a94-b7b8-8fa59b534bb5}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[broken := DIinputNC;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="in_dienst" Id="{1b38962f-6a25-409a-a55f-472be3c898d9}">
      <Declaration><![CDATA[PROPERTY in_dienst : BOOL]]></Declaration>
      <Get Name="Get" Id="{762c4908-66c3-498d-b6be-f13a4816427f}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[in_dienst := not DIinputNC;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>