<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Motor" Id="{7ad6557f-3d41-471e-850d-6874b302dfcd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Motor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	eindeloop_L					: DigitalInput_NO;
	eindeloop_R					: DigitalInput_NO;		
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>