<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Switch_2P" Id="{1844778d-91ff-4d36-98a4-04da56985296}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Switch_2P
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	DI_Input at %I* : bool;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="position0" Id="{f2d4dead-14cd-458e-901d-9a307c79e61a}">
      <Declaration><![CDATA[PROPERTY position0 : BOOL]]></Declaration>
      <Get Name="Get" Id="{2f12a057-fcc5-4a70-a53e-bc0a04fc1234}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[position0 := not DI_Input;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="position1" Id="{39c309c0-e723-4261-b29b-4af7e289ee5a}">
      <Declaration><![CDATA[PROPERTY position1 : BOOL]]></Declaration>
      <Get Name="Get" Id="{1a260927-d8ec-49aa-a2f8-cec52816d6c4}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[position1 := DI_Input;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>