<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FunctionsAndFunctionBlocksex01" Id="{405b5233-a6ad-494c-9ade-7bfcc71bf94f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FunctionsAndFunctionBlocksex01
VAR
number1 		: number;
number2			: number;
sum12			: number;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[number1 + number2 := sum12;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>