<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="safety_ex02" Id="{ce1c7d9e-4364-4980-82f7-aa5ca5b2e030}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM safety_ex02
VAR

M1 					: DigitalOutput;
M1_start			: digitalInput_NO;
M1_stop				: digitalInput_NC;
M1_stop_safe		: digitalInput_NC;
M2					: digitalOutput; 
M4					: digitaloutput;
M5					: digitaloutput;
S1					: digitalInput_NO; 
S2					: digitalInput_NC;
S3					: digitalInput_NO; 
S6					: digitalInput_NC;
S7					: digitalInput_NC;
B4					: digitalInput_NO;
B5					: digitalInput_NO;
P1					: digitaloutput;
P2					: digitaloutput;
P3					: digitaloutput;
P4					: digitaloutput;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//noodstoppen
IF S2.broken OR S6.broken OR S7.broken OR M1_STOP_SAFE.broken OR M1_stop.broken OR S1.isOff THEN
	M1.Off();
END_IF
IF S6.broken OR S7.broken THEN
	P4.On();
END_IF

//noodstop resetten
IF S6.broken OR S7.broken THEN
	P4.On();
END_IF
IF S3.isOn THEN
	P4.Off();
END_IF


//start					//alle stoppen												//veiligheidsdeuren				//start drukknoppen
IF (S2.in_dienst AND M1_STOP_SAFE.in_dienst AND M1_STOP.in_dienst AND P4.Off) AND (B4.isOn AND B5.isOn) AND M1_start.isOn OR S1.isOn THEN
	M1.On();
	M2.On();
END_IF


//stop van de band 
IF S2.broken OR P4.On THEN
	M2.Off();
	P1.On();
END_IF



//veiligheidsdeuren
if S2.broken OR S6.broken OR S7.broken THEN
	M4.On();	(*on betekent dat ze open kunnen*)
	M5.On();	(*on betekent dat ze open kunnen*)
ELSE 
	M4.Off();	(*off betekent dat ze niet open kunnen*)
	M5.Off();	(*off betekent dat ze niet open kunnen*)
END_IF

//sensoren die checken of de deuren toe zijn

IF B4.isOff (*off betekent dat hij geen signaal krijgt dus deur is open*) OR B5.isOff THEN
	P1.On();
ELSE 
	P1.Off();
END_IF

// lamp robot actief
IF M1.On THEN
	P2.On();
ELSE 
	P2.Off();
END_IF

IF S2.broken THEN
	P3.On();
END_IF
IF S1.isOn THEN
	P3.Off();
END_IF









]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>